# -*- coding: utf-8 -*-
"""stock_price_analyzer.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Nhr0YcO8MfgGjvRnh1bIDYjPzNG3N_9k
"""

import numpy as np

prices = np.array([
    100.5, 101.2, 99.8, 102.4, 103.1,
    101.7, 104.2, 105.8, 104.9, 106.3,
    107.1, 106.5, 108.2, 109.7, 108.4,
    110.1, 111.5, 109.8, 112.3, 113.7,
    112.9, 114.2, 115.6, 114.8, 116.3,
    117.1, 116.5, 118.4, 119.2, 120.1
])

average_price = prices.mean()
highest_price = prices.max()
lowest_price = prices.min()


print(f"Average price : {average_price}")
print(f"Highest price : {highest_price}")
print(f"Lowest price : {lowest_price}")

highest_price_index = np.where(prices == highest_price)[0][0]
lowest_price_index = np.where(prices == lowest_price)[0][0]


print(f"The Day with the highest price is : {highest_price_index + 1}")
print(f"The Day with the lowest price is : {lowest_price_index + 1}")

above_average = prices[prices > prices.mean()]


print(above_average)

prices_changes = np.diff(prices)


print(prices_changes)

largest_increase = prices_changes.max()
largest_decrease = prices_changes.min()


print(f"the largest increase is : {largest_increase}")
print(f"the most negative decrease is : {largest_decrease}")

standard_deviation = np.std(prices_changes)


print(f"the standard deviation of daily changes is : {standard_deviation}")